vich_uploader:
    db_driver: orm
    mappings:
        post_images:
            uri_prefix:         '%app.path.post_images%'
            upload_destination: '%kernel.root_dir%/../web/img/posts'

            delete_on_update:   true
            delete_on_remove:   true
