imports:
    - { resource: config_doctrine.yml }
    - { resource: config_doctrine_extensions.yml }
    - { resource: config_easy_admin.yml }
    - { resource: config_fos_user.yml}
    - { resource: config_framework.yml }
    - { resource: config_knp_paginator.yml }
    - { resource: config_parameters.yml }
    - { resource: config_swiftmailer.yml }
    - { resource: config_twig.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
