app:
    resource: '@AppBundle/Controller/PublicPage'
    type: annotation

# At this time only admin account is required, so we only import login route
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# TODO: change to our own controller
easy_admin_bundle:
    resource: "@AppBundle/Controller/Admin/AdminController.php"
    type:     annotation
    prefix:   /admin